<?xml version="1.0"?>
<robot name="omnibot" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="height" value="0.115" />
  <xacro:property name="wheelrad" value="0.05" />
  <xacro:property name="wheellen" value="0.03" />
  <xacro:property name="R" value="0.15" />
  <xacro:property name="R2" value="0.125" />
  <xacro:property name="left_wheel_theta" value="${60/180*pi}" />
  <xacro:property name="back_wheel_theta" value="${180/180*pi}" />
  <xacro:property name="right_wheel_theta" value="${300/180*pi}" />

  <xacro:include filename="$(find nexus_base_ros)/urdf/3WD_Omnibot.gazebo" />
  <xacro:include filename="$(find nexus_base_ros)/urdf/materials.xacro" />
  
  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="base_link"/>
  </joint>
  
  <link name="base_link">
    <visual>
      <geometry>
          <mesh filename="package://nexus_base_ros/meshes/omnibot_body.dae"/>
      </geometry>
      <material name="yellow"/>
    </visual>

		<collision>
			<origin xyz="0 0 ${height/2}" rpy="0 0 0" />
			<geometry>
				<cylinder radius="${R}" length="${height}"/>
			</geometry>
		</collision>
		
		<inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (3*(R*R) + height*height)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (3*(R*R) + height*height)}" iyz="0.0"
	      izz="${mass / 2.0 * (R*R)}"/>
    </inertial>
  </link>

	<link name="left_wheel_link">
		<visual>
			<origin  rpy="${PI/2} 0 0" />
			<geometry>
				<mesh filename="package://nexus_base_ros/meshes/mecanum_wheel.dae"/>
			</geometry>
			<material name="grey"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
			<geometry>
				<cylinder radius="${wheelrad}" length="${wheellen}"/>
			</geometry>
		</collision>
		
		<inertial>
      <origin xyz="0 0 ${wheellen/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (3*(wheelrad*wheelrad) + wheellen*wheellen)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (3*(wheelrad*wheelrad) + wheellen*wheellen)}" iyz="0.0"
	      izz="${mass / 2.0 * (wheelrad*wheelrad)}"/>
    </inertial>
	</link>
	
	<joint name="left_wheel_joint" type="continuous">
		<axis xyz="0 1 0" rpy="0 0 0" />
		<parent link="base_link"/>
		<child link="left_wheel_link"/>
		<origin xyz="${R2*cos(left_wheel_theta)} ${R2*sin(left_wheel_theta)} 0" rpy="0 0 ${left_wheel_theta+PI/2}"/>
		<dynamics damping="0.7"/>
	</joint>


	<link name="back_wheel_link">
		<visual>
			<origin  rpy="${back_wheel_theta+PI/2} 0 0" />
			<geometry>
				<mesh filename="package://nexus_base_ros/meshes/mecanum_wheel.dae"/>
			</geometry>
			<material name="grey"/>
		</visual>
	
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
			<geometry>
				<cylinder radius="${wheelrad}" length="${wheellen}"/>
			</geometry>
		</collision>
		
		<inertial>
      <origin xyz="0 0 ${wheellen/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (3*(wheelrad*wheelrad) + wheellen*wheellen)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (3*(wheelrad*wheelrad) + wheellen*wheellen)}" iyz="0.0"
	      izz="${mass / 2.0 * (wheelrad*wheelrad)}"/>
    </inertial>
	</link>
	
	<joint name="back_wheel_joint" type="continuous">
		<axis xyz="0 1 0" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="back_wheel_link"/>
		<origin xyz="${R2*cos(back_wheel_theta)} ${R2*sin(back_wheel_theta)} 0" rpy="0 0 ${back_wheel_theta-PI/2}"/>
		<dynamics damping="0.7"/>
	</joint>

	<link name="right_wheel_link">
		<visual>
		<origin  rpy="${PI/2} 0 0" />
		<geometry>
			<mesh filename="package://nexus_base_ros/meshes/mecanum_wheel.dae"/>
		</geometry>
		<material name="grey"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
			<geometry>
				<cylinder radius="${wheelrad}" length="${wheellen}"/>
			</geometry>
		</collision>
		
		<inertial>
      <origin xyz="0 0 ${wheellen/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (3*(wheelrad*wheelrad) + wheellen*wheellen)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (3*(wheelrad*wheelrad) + wheellen*wheellen)}" iyz="0.0"
	      izz="${mass / 2.0 * (wheelrad*wheelrad)}"/>
    </inertial>
	</link>
	
	<joint name="right_wheel_joint" type="continuous">
		<axis xyz="0 1 0" rpy="0 0 0" />
		<parent link="base_link"/>
		<child link="right_wheel_link"/>
		<origin xyz="${R2*cos(right_wheel_theta)} ${R2*sin(right_wheel_theta)} 0" rpy="0 0 ${right_wheel_theta+PI/2}"/>
		<dynamics damping="0.7"/>
	</joint>

	<link name="lidar_link">
		<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<mesh filename="package://nexus_base_ros/meshes/RPLIDAR_A1M8.dae"/>
		</geometry>
		<material name="dark_grey"/>
		</visual>
	</link>
	<joint name="lidar_joint" type="fixed">
		<parent link="base_link"/>
		<child link="lidar_link"/>
		<origin xyz="0.095 0 0.115" rpy="0 0 0" />
	</joint>

  <transmission name="left_wheel_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="back_wheel_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_wheel_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="back_wheel_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_wheel_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
